sudo : false

language: node_js

node_js:
   - "5"
   - "5.1"
   - "4"
   - "4.2"
   - "4.1"
   - "4.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9

services:
  - mongodb

after_success:
  - npm run coveralls
